//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwiPraca {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EwiPraca.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd, spróbuj ponownie lub skontaktuj się z Administratorem aplikacji..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EwiPracaImportPracownikowSzablon {
            get {
                object obj = ResourceManager.GetObject("EwiPracaImportPracownikowSzablon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Media\ImportEmployeesDataFiles.
        /// </summary>
        internal static string ImportEmployeesExcelTemplatesFolderPath {
            get {
                return ResourceManager.GetString("ImportEmployeesExcelTemplatesFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny NIP..
        /// </summary>
        internal static string IncorrectNIPMessage {
            get {
                return ResourceManager.GetString("IncorrectNIPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny numer PESEL..
        /// </summary>
        internal static string IncorrectPESELMessage {
            get {
                return ResourceManager.GetString("IncorrectPESELMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny REGON..
        /// </summary>
        internal static string IncorrectREGONMessage {
            get {
                return ResourceManager.GetString("IncorrectREGONMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj, w dniu {0} upływa termin ważności badań lekarskich dla Twojego pracownika {1} w firmie {2}. Pozdrawiamy, zespół EwiPraca..
        /// </summary>
        internal static string MedicalResultToExpireReminderEmailBody {
            get {
                return ResourceManager.GetString("MedicalResultToExpireReminderEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upływa termin ważności badań lekarskich..
        /// </summary>
        internal static string MedicalResultToExpireReminderEmailTitle {
            get {
                return ResourceManager.GetString("MedicalResultToExpireReminderEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj, w dniu {0} upływa termin ważności szkolenia BHP  dla Twojego pracownika {1} w firmie {2}. Pozdrawiamy, zespół EwiPraca. .
        /// </summary>
        internal static string OSHTrainingToExpireReminderEmailBody {
            get {
                return ResourceManager.GetString("OSHTrainingToExpireReminderEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upływa termin ważności szkolenia BHP..
        /// </summary>
        internal static string OSHTrainingToExpireReminderEmailTitle {
            get {
                return ResourceManager.GetString("OSHTrainingToExpireReminderEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Witaj!&lt;/p&gt;
        ///&lt;p&gt;Oto link do zresetowania Twojego hasla w aplikacji EwiPraca:&lt;/p&gt;
        ///&lt;a href=&quot;XXXLINK&quot;&gt;Kliknij tutaj&lt;/a&gt;
        ///&lt;p&gt;Link jest wazny do XXXDATE.&lt;/p&gt;
        ///&lt;p&gt;Jesli to nie Ty generowales link, zignoruj te wiadomosc.&lt;/p&gt;.
        /// </summary>
        internal static string PasswordResetEmailBody {
            get {
                return ResourceManager.GetString("PasswordResetEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetowanie hasła EwiPraca.
        /// </summary>
        internal static string PasswordResetEmailTitle {
            get {
                return ResourceManager.GetString("PasswordResetEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole Notatki może mieć maksymalnie 1000 znaków..
        /// </summary>
        internal static string TooLongCompanyNotesMessage {
            get {
                return ResourceManager.GetString("TooLongCompanyNotesMessage", resourceCulture);
            }
        }
    }
}
